
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_ABRE = 5;
  public static final int MULT = 4;
  public static final int SUM = 3;
  public static final int error = 1;
  public static final int FIN_CADENA = 2;
  public static final int PAR_CIERRA = 6;
  public static final int DIGITO = 7;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FIN_CADENA",
  "SUM",
  "MULT",
  "PAR_ABRE",
  "PAR_CIERRA",
  "DIGITO"
  };
}

